version: '3.8'

services:
  postgres-slave:
    image: postgres:15
    container_name: student-postgres-slave
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: exam_db
    volumes:
      - postgres_slave_data:/var/lib/postgresql/data
    entrypoint:
      - bash
      - -c
      - |
        # Jika direktori data postgres kosong, lakukan backup awal dari Master Laptop 1
        if [ ! -s /var/lib/postgresql/data/PG_VERSION ]; then
          echo "Memulai backup data dari Master (Laptop 1)..."
          PGPASSWORD=replpassword pg_basebackup -h 10.206.80.189 -p 5432 -U replicator -D /var/lib/postgresql/data -Fp -Xs -P -R
          
          # PERBAIKAN: Ubah kepemilikan file kembali ke user postgres
          chown -R postgres:postgres /var/lib/postgresql/data
          chmod 700 /var/lib/postgresql/data
        fi
        echo "Memulai PostgreSQL dalam Mode Standby..."
        exec gosu postgres postgres -c hot_standby=on

volumes:
  postgres_slave_data:
