version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: student-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
      - ./mongodb.key:/opt/keyfile/mongodb.key:ro
    entrypoint:
      - bash
      - -c
      - |
        cp /opt/keyfile/mongodb.key /data/mongodb.key
        chmod 400 /data/mongodb.key
        chown 999:999 /data/mongodb.key
        exec docker-entrypoint.sh mongod --replSet rs0 --keyFile /data/mongodb.key --bind_ip_all --auth
    ports:
      - "27018:27017"

volumes:
  mongodb_data:
