version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mongodb
      - postgres

  mongodb:
    image: mongo:latest
    container_name: mongodb-lms
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db

  postgres:
    image: postgres:latest
    container_name: postgres-lms
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: lms
    volumes:
      - postgres_data_lms_v2:/var/lib/postgresql

volumes:
  mongodb_data:
  postgres_data_lms_v2: